
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRNOTEQ = 30;
  public static final int DIVIDE = 36;
  public static final int SUBSTRING = 21;
  public static final int READSTR = 19;
  public static final int GE = 27;
  public static final int CONCATENATE = 20;
  public static final int READINT = 16;
  public static final int LPAREN = 38;
  public static final int SEMI = 31;
  public static final int MINUS = 34;
  public static final int RPAREN = 39;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int LT = 24;
  public static final int OR = 3;
  public static final int COMMA = 32;
  public static final int BEGIN = 7;
  public static final int NUM = 40;
  public static final int PLUS = 33;
  public static final int EXIT = 9;
  public static final int ASSIGN = 22;
  public static final int IF = 10;
  public static final int LE = 25;
  public static final int EOF = 0;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int MODE = 37;
  public static final int IDENT = 41;
  public static final int EQ = 23;
  public static final int TIMES = 35;
  public static final int ELSE = 12;
  public static final int POSITION = 18;
  public static final int WHILE = 13;
  public static final int THEN = 11;
  public static final int NE = 28;
  public static final int END = 8;
  public static final int STRING = 42;
  public static final int STREQ = 29;
  public static final int FALSE = 6;
  public static final int GT = 26;
  public static final int PRINT = 15;
  public static final int LENGTH = 17;
  public static final int DO = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "BEGIN",
  "END",
  "EXIT",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "PRINT",
  "READINT",
  "LENGTH",
  "POSITION",
  "READSTR",
  "CONCATENATE",
  "SUBSTRING",
  "ASSIGN",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "STREQ",
  "STRNOTEQ",
  "SEMI",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODE",
  "LPAREN",
  "RPAREN",
  "NUM",
  "IDENT",
  "STRING"
  };
}

