
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRNOTEQ = 33;
  public static final int DIVIDE = 39;
  public static final int SUBSTRING = 23;
  public static final int READSTR = 21;
  public static final int INCREMENT = 43;
  public static final int CONST = 50;
  public static final int GE = 30;
  public static final int CONCATENATE = 22;
  public static final int READINT = 18;
  public static final int INTEGER = 49;
  public static final int LPAREN = 41;
  public static final int SEMI = 34;
  public static final int DECREMENT = 44;
  public static final int MINUS = 37;
  public static final int RPAREN = 42;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int LT = 27;
  public static final int OR = 3;
  public static final int COMMA = 35;
  public static final int BEGIN = 9;
  public static final int NUM = 45;
  public static final int PLUS = 36;
  public static final int EXIT = 11;
  public static final int MAIN = 54;
  public static final int ASSIGN = 25;
  public static final int IF = 12;
  public static final int LE = 28;
  public static final int BOOLEAN = 48;
  public static final int EOF = 0;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int ENDFUNC = 53;
  public static final int MODE = 40;
  public static final int FILEOUT = 24;
  public static final int IDENT = 46;
  public static final int EQ = 26;
  public static final int TIMES = 38;
  public static final int TUP = 51;
  public static final int SUPTRUE = 7;
  public static final int ELSE = 14;
  public static final int FUNC = 52;
  public static final int POSITION = 20;
  public static final int WHILE = 15;
  public static final int THEN = 13;
  public static final int NE = 31;
  public static final int END = 10;
  public static final int STRING = 47;
  public static final int SUPFALSE = 8;
  public static final int STREQ = 32;
  public static final int FALSE = 6;
  public static final int GT = 29;
  public static final int PRINT = 17;
  public static final int LENGTH = 19;
  public static final int DO = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "SUPTRUE",
  "SUPFALSE",
  "BEGIN",
  "END",
  "EXIT",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "PRINT",
  "READINT",
  "LENGTH",
  "POSITION",
  "READSTR",
  "CONCATENATE",
  "SUBSTRING",
  "FILEOUT",
  "ASSIGN",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "STREQ",
  "STRNOTEQ",
  "SEMI",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODE",
  "LPAREN",
  "RPAREN",
  "INCREMENT",
  "DECREMENT",
  "NUM",
  "IDENT",
  "STRING",
  "BOOLEAN",
  "INTEGER",
  "CONST",
  "TUP",
  "FUNC",
  "ENDFUNC",
  "MAIN"
  };
}

